# wrangler.toml
name = 'ham-page-w2sz'
main = "workers/index.js"
compatibility_date = "2025-04-15"

# Configuration for the production environment
workers_dev = true
routes = ["dash.w2sz.org/*"]

[site]
bucket = "./src"
